spring.application.name=Api-GateWay

server.port=3333
management.endpoint.web.exposure.include=*
management.endpoint.health.show-details=always

spring.boot.admin.client.url=http://localhost:1111

spring.cloud.gateway.discovery.locator.enable=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=greet-api
spring.cloud.gateway.routes[0].id.uri=lb://GREET-API
spring.cloud.gateway.routes[0].predicate[0]=path=/greet


spring.cloud.gateway.routes[1].id=greet-api
spring.cloud.gateway.routes[1].id.uri=lb://WELCOMEAPI
spring.cloud.gateway.routes[1].predicate[0]=path=/welcome



